apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployments/nginx.yaml
  - ./services/nginx.yaml
  - ./configMaps/config.yaml

commonAnnotations:
  owner: niki
  project: games-admin-static
  repo: https://syngit.txxcd.com/niki/games-admin-static.git
  updatedBy: kustomize

images:
- name: syngit.txxcd.com:4567/niki/games-admin-static
  newName: syngit.txxcd.com:4567/niki/games-admin-static
  newTag: latest
- name: syngit.txxcd.com:4567/docker/config-sync
  newName: syngit.txxcd.com:4567/docker/config-sync
  newTag: latest
