apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    qcloud-app: games-admin-static-hpa
  name: games-admin-static-hpa
spec:
  maxReplicas: 20
  targetCPUUtilizationPercentage: 90
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: games-admin-static
