apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin-static
spec:
  template:
    spec:
      containers:
        - name: games-admin-static
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
