apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    k8s-app: update-aws-cdn
  name: update-aws-cdn
  namespace: niki-pro
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        k8s-app: update-aws-cdn
    spec:
      containers:
        - image: registry-pro.maitang.co/docker/aws-cli:cf-niki-games-admin-static
          imagePullPolicy: IfNotPresent
          name: update-aws-cdn
          command: ["/bin/sh", "-c", "/update-cdn.sh"]
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: tencent-registry-maitang
      restartPolicy: OnFailure


