apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin-static
spec:
  template:
    spec:
      containers:
        - name: games-admin-static
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
