apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin-static
spec:

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      terminationGracePeriodSeconds: 15
      imagePullSecrets:
        - name: tencent-registry-maitang
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values:
                      - ON_DEMAND
