apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-admin-static
spec:
  template:
    spec:
      containers:
        - name: games-admin-static
          resources:
            requests:
              cpu: 10m
              memory: 80Mi
            limits:
              cpu: 100m
              memory: 128Mi
